'use client'

import { useState } from 'react'
import { Activity, BarChart3, Bell, BookOpen, ChevronRight, CircleHelp, Database, FileUp, GitCompare, LayoutDashboard, ListChecks, Map, Search, Settings, ShieldCheck, Upload, Users } from 'lucide-react'

type View = 'overview' | 'upload' | 'review' | 'canonical' | 'mappings' | 'benchmark'
const reviews = [
  ['CPSE-NTPC-1187', 'CNMC-042019', '78%', 'Pressure class differs: 150 vs 300'],
  ['CPSE-BHEL-2204', 'CNMC-117204', '69%', 'Material grade is not present in source'],
  ['CPSE-IOCL-0812', 'CNMC-311008', '62%', 'Actuation type conflicts with canonical record'],
]
const nav = [['overview', 'Overview', LayoutDashboard], ['upload', 'Upload & Validate', Upload], ['review', 'Review Queue', ListChecks], ['canonical', 'Canonical Registry', BookOpen], ['mappings', 'CPSE Mappings', GitCompare], ['benchmark', 'Benchmark', BarChart3]] as const
function Badge({ children, tone = 'blue' }: { children: React.ReactNode; tone?: string }) { return <span className={`badge ${tone}`}>{children}</span> }
function Sidebar({ view, setView }: { view: View; setView: (v: View) => void }) { return <aside className="sidebar"><div className="india-mark"><Map size={31} strokeWidth={1.2} /></div><div className="brand"><b>Bharath Mati</b><small>One Nation – One Material Code</small></div><nav className="nav">{nav.map(([id, label, Icon]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => setView(id)}><Icon size={17} />{label}</button>)}</nav><div className="nav-divider" /><nav className="nav"><button><Settings size={17} />Settings</button><button><CircleHelp size={17} />Help & Support</button></nav><div className="sidebar-bottom"><div className="tricolor"><i /><i /><i /></div><div className="emblem">◈</div><b>Government of India</b><small>SIH 2024 · Governed workspace</small></div></aside> }
function Header({ view }: { view: View }) { const label = nav.find(n => n[0] === view)?.[1] ?? 'Overview'; return <header className="topbar"><div><div className="crumb">Bharath Mati / {label}</div><div className="top-title">{label}</div></div><div className="top-actions"><div className="search"><Search size={15} /><input placeholder="Search materials, codes, CPSEs..." /></div><div className="health"><span className="dot" />All systems operational</div><Bell size={18} color="var(--muted)" /><div className="avatar">AD</div><span className="admin-name">Admin</span></div></header> }
function Hero() { return <div className="hero"><div><div className="hero-kicker">NATIONAL MATERIAL REGISTRY</div><h1>Bharath Mati</h1><p>One Nation – One Material Code</p></div><div className="hero-photo"><img src="/government-building.png" alt="Indian government institutional building with national flag" /><div className="hero-wash" /></div></div> }
function Kpis() { const data = [['Source Records', '10,000', 'Across 6 CPSE systems', Database], ['Canonical Materials', '6,842', '31.6% duplicate reduction', BookOpen], ['Pending Reviews', '1,247', 'Requires expert attention', ListChecks], ['Mapping Coverage', '94.8%', '+2.4% this period', GitCompare]] as const; return <div className="kpis">{data.map(([label, value, foot, Icon], i) => <div className="card kpi" key={label}><div className="kpi-top"><span>{label}</span><Icon size={17} className={`kpi-icon icon-${i}`} /></div><strong>{value}</strong><small className={i === 2 ? 'warning' : 'positive'}>{foot}</small></div>)}</div> }
function Outcomes() { return <div className="card analytics outcomes-card"><div className="card-head"><div><h2>Harmonization Outcomes</h2><div className="card-sub">Latest processed batch</div></div><Badge tone="green">10,000 records</Badge></div><div className="outcomes"><div className="donut"><div><b>10K</b><small>Records</small></div></div><div className="legend">{[['Equivalent', '6,214', '62.1%', 'green'], ['Review', '1,698', '17.0%', 'amber'], ['Different', '2,088', '20.9%', 'red']].map(([name, value, pct, tone]) => <div className="legend-row" key={name}><span className="legend-label"><i className={`swatch ${tone}`} />{name}</span><span className="metric">{value} <small>{pct}</small></span></div>)}</div></div></div> }
function Quality() { return <div className="card analytics"><div className="card-head"><div><h2>Quality Indicators</h2><div className="card-sub">Benchmark suite · 10K run</div></div><ShieldCheck size={18} color="var(--green)" /></div><div className="quality">{[['Precision', '96.2%', 96], ['Recall', '93.8%', 94], ['F1 Score', '94.9%', 95]].map(([label, value, width]) => <div className="quality-row" key={label}><div><span>{label}</span><b>{value}</b></div><div className="progress"><i style={{ width: `${width}%` }} /></div></div>)}<div className="safety"><span>Near-miss Safety</span><Badge tone="green">PASS</Badge></div></div></div> }
function ActivityPanel() { return <div className="card analytics"><div className="card-head"><div><h2>Recent Activity</h2><div className="card-sub">Governance events</div></div><Activity size={18} color="var(--blue)" /></div><div className="timeline">{[['Material batch processed', '10,000 records · 12 min ago'], ['New items in review queue', '83 records · 1 hr ago'], ['Canonical material updated', 'CNMC-042019 · 3 hrs ago'], ['Benchmark run completed', '10K suite · Yesterday']].map(([title, meta]) => <div className="timeline-item" key={title}><span /><div><b>{title}</b><small>{meta}</small></div></div>)}</div></div> }
function QuickActions({ setView }: { setView: (v: View) => void }) { const actions = [['Upload & Validate', 'Submit CPSE material extracts', Upload, 'upload'], ['Review Queue', 'Resolve uncertain matches', ListChecks, 'review'], ['Canonical Registry', 'Browse governed identities', BookOpen, 'canonical'], ['CPSE Mappings', 'Inspect source relationships', GitCompare, 'mappings']] as const; return <div className="quick"><div className="section-label">Quick actions</div><div className="quick-grid">{actions.map(([title, text, Icon, id]) => <button className="quick-card" key={title} onClick={() => setView(id)}><span className="quick-icon"><Icon size={18} /></span><span><b>{title}</b><small>{text}</small></span><ChevronRight size={16} /></button>)}</div></div> }
function Overview({ setView }: { setView: (v: View) => void }) { return <><Hero /><Kpis /><div className="analytics-grid"><Outcomes /><Quality /><ActivityPanel /></div><QuickActions setView={setView} /></> }
function ReviewView() { return <><div className="section-head"><div><div className="eyebrow">Human-in-the-loop governance</div><h1>Review Queue</h1><p>Resolve uncertain pairwise matches before canonical publication.</p></div><Badge tone="amber">1,247 pending</Badge></div><div className="card"><div className="filters"><div className="search inline"><Search size={15} /><input placeholder="Search records or IDs" /></div><select><option>All statuses</option><option>Pending</option><option>Approved</option></select><select><option>Any confidence</option><option>Below 70%</option><option>70–85%</option></select></div><div className="table-wrap"><table><thead><tr><th>Source record</th><th>Candidate</th><th>Confidence</th><th>Finding</th><th>Status</th></tr></thead><tbody>{reviews.map(r => <tr key={r[0]}><td><b>{r[0]}</b></td><td>{r[1]}</td><td><b>{r[2]}</b></td><td>{r[3]}</td><td><Badge tone="amber">REVIEW</Badge></td></tr>)}</tbody></table></div></div></> }
function RegistryView() { return <><div className="section-head"><div><div className="eyebrow">Authoritative CNMC registry</div><h1>Canonical Registry</h1><p>Governed material identities and their CPSE memberships.</p></div><div className="search inline"><Search size={15} /><input placeholder="Search canonical materials" /></div></div><div className="card"><div className="table-wrap"><table><thead><tr><th>CNMC identifier</th><th>Canonical description</th><th>Members</th><th>Source systems</th><th>State</th></tr></thead><tbody>{[['CNMC-042019', 'Gate valve, forged steel, class 300', '38', 'NTPC / BHEL'], ['CNMC-117204', 'Centrifugal process pump, horizontal split case', '24', 'BHEL / GAIL'], ['CNMC-311008', 'Industrial pressure gauge, SS316, 100mm dial', '19', 'IOCL / ONGC']].map(r => <tr key={r[0]}><td><b className="link">{r[0]}</b></td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td><Badge tone="green">GOVERNED</Badge></td></tr>)}</tbody></table></div></div></> }
function GenericView({ view }: { view: View }) { const title = nav.find(n => n[0] === view)?.[1] ?? 'Dashboard'; return <><div className="section-head"><div><div className="eyebrow">Bharath Mati workspace</div><h1>{title}</h1><p>Connected to the governed material harmonization service.</p></div><Badge tone="green">Operational</Badge></div><div className="card empty-panel"><Database size={25} /><h2>{title} workspace</h2><p>Use the existing service integration to manage this area of the registry.</p></div></> }
export default function Page() { const [view, setView] = useState<View>('overview'); const content = view === 'overview' ? <Overview setView={setView} /> : view === 'review' ? <ReviewView /> : view === 'canonical' ? <RegistryView /> : <GenericView view={view} />; return <div className="app"><Sidebar view={view} setView={setView} /><main className="main"><Header view={view} /><section className="content">{content}</section></main></div> }
